### PR TITLE
Add code challenge as default and client secret as optional

### PR DESCRIPTION
**Pull request by rohitggarg-qb**
Please see issue #39 for more information about why this PR came into existence

Functionality added so far:
1. Add generator for code challenge
2. Add storage in the cookies of browser session for code challenge
3. Request the token with code challenge instead of secret if code challenge is set previously

Need help:
1. How do I test it?
2. How do I add test cases for it?

Thanks

### CODE REVIEW

**Comment by rohitggarg-qb** [comment]
@payton would appreciate if I could get some help in closing the testing part

**Comment by payton** [comment]
This library is definitely in need of some well-defined tests. One thought that come to mind is using a mocker for axios and writing tests for all supported error/success responses as defined in the respective standards documents (openid, pkce, etc).

I think it will also be useful to break the current implementation up in to smaller functions that can be tested individually.

One comment on your PR, is there any reason why this is being added as part of the openid implementation? I would prefer to keep standards separate despite the inevitable code duplication.

**Comment by rohitggarg-qb** [comment]
> One comment on your PR, is there any reason why this is being added as part of the openid implementation? I would prefer to keep standards separate despite the inevitable code duplication.

One of the reasons is to avoid duplication. The other reason is, Okta App's SECRET value has also become optional in this case. 
If you feel that's a better design I can make the changes in that fashion. Could you help me by replying back as to what's going through your mind when you say ```keep the standards separate```?

**Comment by payton** [comment]
By `keep standards separate`, I'm referring to RFC standards. That terminology is a little off in the case of OpenID Connect, but ultimately OpenID connect was built off of RFC 6749 while PKCE is defined in RFC 7636. Since they both have clear rules to follow, despite some overlapping, I thought it may be good to keep them separate. Do you agree?

**Comment by payton** [comment]
* This was not followed with the github implementation but may be good moving forward

**Comment by payton** [comment]
Just following up, @rohitggarg-qb

**Comment by rohitggarg-qb** [comment]
Aah okay. I will try to make these changes and create separate flows for pkce.
Thanks!

**Comment by rohitggarg-qb** [comment]
@payton I have tested this out manually on cloudfront. How does this look?
Thanks!

**Comment by payton** [comment]
Hey @rohitggarg-qb sorry on the delay. Wrapping up my summer and have been busy. I'm planning on getting some non-work work done tomorrow morning and will try to get this reviewed then.

**Comment by rohitggarg-qb** [comment]
@payton Thanks for the review, I shall make the changes and drop a message so you could take it further.

Thanks for your time.

**Comment by rohitggarg-qb** [comment]
@payton FYI

**Comment by payton** [comment]
Perfect. Thank you for your contribution, @rohitggarg-qb !

**Pull request merged**
